var http = require("http"),
    url = require("url");

var restaurants = {
    '1492 Tapas Bar': [],
    '312 Chicago': [],
    '676 Restaurant & Bar': [],
    'Ai Japanese Restaurant & Lounge': [],
    'Aja': [],
    'Alhambra Palace': [],
    'Allgauer\'s on the Riverfront': [],
//    'American Girl Cafe': [],
    'Aquitaine': [],
    'Aria': [],
    'Athena Restaurant': [],
    'Atwaters Restaurant': [],
    'Atwood Cafe': [],
    'Benihana': [],
    'Benihana | Lombard': [],
    'Benihana | Schaumburg': [],
    'Benny\'s Chop House': [],
    'Berghoff Restaurant': [],
    'Bistro 110': [],
    'Bistro Bordeaux': [],
    'Bistro Campagne': [],
    'bistronomic': [],
    'Bistrot Margot': [],
    'Bistrot Zinc': [],
    'Blackbird': [],
    'Blue 13': [],
    'BOKA': [],
    'Branch 27': [],
    'The Bristol': [],
    'Buddy Guy\'s Legends': [],
    'Cafe Ba-Ba-Reeba': [],
    'Café des Architectes': [],
    'Cafe Spiaggia': [],
    'Caliterra Restaurant': [],
    'Cape Cod Room': [],
    'The Capital Grille': [],
    'The Capital Grille | Lombard': [],
    'The Capital Grille | Rosemont': [],
    'Carlucci Rosemont': [],
    'Carmichaels Chicago Steakhouse': [],
    'Carmine\'s': [],
    'Carnivale': [],
    'Carson\'s Ribs & Steaks': [],
    'Catch 35': [],
    'Catch 35 | Naperville': [],
    'Chicago Curry House': [],
    'Chicago Cut Steakhouse': [],
    'Chicago Firehouse Restaurant': [],
    'Chicago Prime Steakhouse': [],
    'Chicago Q': [],
    'China Grill': [],
    'Chizakaya Japanese Pub': [],
    'C-House': [],
    'Cibo Matto': [],
    'Coco Pazzo': [],
    'Connie\'s Pizza': [],
    'David Burke\'s Primehouse': [],
    'De Cero': [],
    'deca Restaurant and Bar': [],
    'Devon Seafood Grill': [],
    'Dick\'s Last Resort': [],
    'Dine': [],
    'Ditka\'s Restaurant': [],
    'Dos Diablos': [],
    'The Drawing Room': [],
    'Duchamp': [],
    'East Bank Club': [],
    'Maxwell\'s at the Club': [],
    'Eatt': [],
    'Elate': [],
    'EPIC': [],
    'Fiorentino\'s Cucina': [],
    'Fleming\'s Prime Steakhouse & Wine Bar': [],
    'Fogo de Chao': [],
    'Fornetto Mei': [],
    'Frontera Grill': [],
    'Fulton\'s on the River': [],
    'The Gage': [],
    'Geja\'s Cafe': [],
    'Gemini Bistro': [],
    'Gioco': [],
    'Gyu-Kaku': [],
    'Hard Rock Cafe': [],
    'Harry Caray\'s Italian Steakhouse': [],
    'Harry Caray\'s Italian Steakhouse | Rosemont': [],
    'House of Blues Back Porch': [],
    'Hub 51': [],
    'Hugo\'s Frog Bar': [],
    'Il Mulino New York': [],
    'Indian Garden Restaurant': [],
    'IPO': [],
    'Italian Village Restaurants': [],
    'Jack Binion\'s Steak House': [],
    'Japonais': [],
    'Joe\'s Seafood, Prime Steak & Stone Crab': [],
    'Keefer\'s Restaurant': [],
    'Kinzie Chop House': [],
    'La Cantina Grill': [],
    'La Madia': [],
    'La Sardine': [],
    'Landmark Grill': [],
    'Las Tablas Colombian Steakhouse': [],
    'Lawry\'s The Prime Rib': [],
    'Le Colonial': [],
    'LM Restaurant': [],
    'The Lobby at The Peninsula': [],
    'Lockwood': [],
    'The Market Bistro': [],
//    'Market Restaurant and Sports Bar': [],       // Found but need to have sports bar and that is not in the name
    'Markethouse': [],
    'May St Café': [],
    'McCormick & Schmick\'s Seafood Restaurant': [],
//    'McCormick & Schmick\'s Seafood Restaurant | Chestnut': [],
    'Medi by Bice': [],
    'Mei\'s Corner': [],
    'Melting Pot': [],
    'Mercadito': [],
    'Mercat A La Planxa': [],
    'Merlo on Maple': [],
    'Mexique': [],
    'Mirabell Restaurant': [],
    'Mirai': [],
    'Mitchell\'s Fish Market': [],
    'Moe\'s Cantina | River North': [],
    'Mon Ami Gabi': [],
    'Mon Ami Gabi | Oak Brook': [],
    'Morton\'s The Steakhouse | Northbrook': [],
    'Morton\'s The Steakhouse': [],
    'Morton\'s The Steakhouse | Schaumburg': [],
    'N9NE Steakhouse': [],
    'Nacional 27': [],
    'Naha': [],
    'Nia': [],
    'Nick\'s Fishmarket Grill & Bar': [],
    'O\'Briens Restaurant and Bar': [],
    'Oceanique': [],
    'one sixtyblue': [],
    'Orso\'s': [],
    'Osteria Via Stato': [],
    'Palm Restaurant': [],
    'Pane Caldo': [],
    'Park Grill': [],
    'Perennial': [],
    'Petterino\'s': [],
    '437 Rush Restaurant': [],
    'Piccolo Sogno': [],
    'Prairie Fire': [],
    'Prix Fixe': [],
    'Prosecco': [],
    'Province': [],
    'Purple Pig': [],
    'Quartino': [],
    'RJ Grunts': [],
    'RB Grille': [],
    'The Red Canary': [],
    'Red Light': [],
    'Conrad Hotel': [],
    'Rhapsody': [],
    'Riccardo Trattoria': [],
    'Riva Navy Pier': [],
    'The Rosebud': [],
    'Rosebud on Rush': [],
    'Rosebud Prime': [],
    'Rosebud Steakhouse': [],
    'Rosebud Theater District': [],
    'Rosebud Trattoria': [],
    'Roy\'s Restaurant': [],
    'Ruth\'s Chris Steak House': [],
    'Ruth\'s Chris Steak House | Northbrook': [],
    'Sable Kitchen & Bar': [],
    'The Saloon Steakhouse': [],
    'Salpicón': [],
    'Salute Wine Bar': [],
    'Sam & Harry\'s Steak House | Schaumburg': [],
    'Scoozi': [],
    'Seasons Restaurant': [],
    'Sepia': [],
    'Shaw\'s Crab House': [],
    'Shula\'s Steak House': [],
    'Smith & Wollensky': [],
    'South Water Kitchen': [],
    'State and Lake Restaurant': [],
    'Sullivan\'s Steakhouse': [],
    'SushiSamba Rio': [],
    'Tapas Valencia': [],
    'Tarantino\'s': [],
    'Tavern at the Park': [],
    'Tavern on Rush': [],
    'Terzo Piano': [],
    'Texas De Brazil | Downtown Chicago': [],
    'Topolobampo': [],
    'Trattoria Isabella': [],
    'Trattoria No. 10': [],
    'Tuscany Restaurant': [],
    'Veerasway': [],
    'Vermilion': [],
    'VIAND  Bar and Kitchen': [],
    'Vie | Western Springs': [],
    'Vivo Restaurant': [],
    'The Walnut Room': [],
    'Wave Restaurant': [],
    'Weather Mark Tavern': [],
    'Weber Grill Restaurant': [],
    'Wildfire | Chicago': [],
    'Wildfire | Glenview': [],
    'Wildfire | Lincolnshire': [],
    'Wildfire | Oakbrook': [],
    'Wildfire | Schaumburg': [],
    'Zapatista': [],
    'Zealous Restaurant': [],
    'Zest Restaurant': [],
    'Zocalo Restaurant & Tequila Bar': []
}

for (var name in restaurants) {
    if (restaurants.hasOwnProperty(name)) {
        getBusinessInfo(name);
    }
}
function getBusinessInfo(name, city) {
    var components = name.split(" | ");

    var lowerName = components[0].toLowerCase(),
        city = components[1] || "Chicago";

    var href = "http://api.yelp.com/business_review_search"
            + "?term=" + encodeURIComponent(name)
            + "&location=" + encodeURIComponent(city + ", IL")
            + "&ywsid=",            // TODO : Append Yelp API key here
        hrefFields = url.parse(href),
        options = {
            host: hrefFields.hostname,
            port: hrefFields.port || 80,
            path: (hrefFields.pathname || "") + (hrefFields.search || "")
        };

    var data = [];
    http.get(options, function(res) {
        res.on("data", function(chunk) {
            data.push(chunk);
        });
        res.on("end", function() {
            var businesses = JSON.parse(data.join("")).businesses,
                business = [],
                halt = false;
            businesses.forEach(function(el) {
                if (el.name.toLowerCase() === lowerName) {
                    business = [el];
                    halt = true;
                } else if (!halt && el.name.toLowerCase().indexOf(lowerName) >= 0) {
                    business.push(el);
                }
            });
            restaurants[name] = business;
            if (business.length !== 1) {
                console.log("Yelp lookup failure: ", name, business.length, businesses.map(function(el) { return el.name; }));
            }
        });
    }).on("error", function(e) {
        console.info("error", e);
    });
}

exports.restaurants = restaurants;
